swagger: "2.0"
info:
  version: "0.0.1"
  title: Cure App - Major Project

host: localhost:3000
basePath: /

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      The following syntax must be used in the 'Authorization' header :
      "Bearer {token}"

paths:
  /user:
    x-swagger-router-controller: main_controller
    post:
      description: Add User
      operationId: createUser
      parameters:
        - name: newUser
          in: body
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Message"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Message"
    get:
      description: User profile
      operationId: getUser
      security:
        - Bearer: []
      x-security-scopes:
        - user
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Message"

  /auth/login:
    x-swagger-router-controller: main_controller
    post:
      description: Login User
      operationId: loginUser
      parameters:
        - name: userLogin
          in: body
          schema:
            $ref: "#/definitions/UserLogin"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Message"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Message"

# -----------------------------------------------------------
definitions:
  Message:
    required:
      - message
    properties:
      message:
        type: string

  NewUser:
    required:
      - name
      - email
      - password
    properties:
      name:
        type: string
      email:
        type: string
      password:
        type: string
      role:
        type: string
  User:
    properties:
      uid:
        type: string
      name:
        type: string
      email:
        type: string
      password:
        type: string
      role:
        type: string
      create_time:
        type: string
  UserLogin:
    required:
      - email
      - password
    properties:
      email:
        type: string
      password:
        type: string
